### PR TITLE
Add esy-manifests for luv-lwt and luv-promise

### PR DESCRIPTION
**Pull request by lessp**
~I'm getting errors while building both~, but this might be a valid approach for having `esy`-manifests for the `Lwt` and `Promise` implementations!

### CODE REVIEW

**Comment by aantron** [comment]
@lessp, is this happening when you are trying to build only `luv` itself?

`luv_promise` and `luv_lwt` are kind of experimental packages, I don't know what their ultimate fate is, but they are in this repo for now. I would hope their builds aren't triggered by trying to build the main package.

**Comment by aantron** [comment]
All the errors look related to the recent vendored libuv version upgrade. All the problem identifiers are things that were introduced between libuv 1.32.0 and 1.34.0, and I just added bindings for. I wonder what is causing this. What command did you issue to start this build?

**Comment by lessp** [comment]
> @lessp, is this happening when you are trying to build only `luv` itself?
> 
> `luv_promise` and `luv_lwt` are kind of experimental packages, I don't know what their ultimate fate is, but they are in this repo for now. I would hope their builds aren't triggered by trying to build the main package.

I believe the issues springs from me trying to use `esy` here. I've had `luv` building a few times, but am mainly trying to use it as a dependency. 

Currently I'm getting an error for `promise` which reports no matching packages. 

```
No package matching:
  luv -> @opam/luv -> @opam/promise@>=opam:1.0.0
```

**Comment by aantron** [comment]
This error looks like esy is misinterpreting the opam file, or something like that:

```
No package matching:
  luv -> @opam/luv -> @opam/promise@>=opam:1.0.0
```

because `promise` is only a `dev` dep, because it is needed for one of the examples:

https://github.com/aantron/luv/blob/e0788bd840219427a2744963f11fff68f2d20087/luv.opam#L28

Does esy assume that `luv` resolved to a repo is a dev build, and therefore try to pull this dependency?

Also, `promise` has an opam resolution, but I think it shouldn't be installed at all:

https://github.com/aantron/luv/blob/e0788bd840219427a2744963f11fff68f2d20087/luv.opam#L31-L33

I can probably just remove it from the opam file, and have Travis install it manually for its build.

**Comment by aantron** [comment]
As for the NPM `reason-promise` package, that's the JS version of `promise` (and the main one). But it can't be used by luv, because luv is native :) This is a dep on the native implementation of promise (from its `src/native` dir), which is not released to opam, so has to be built from the dev repo ATM, or, again, it's easier to just remove it :)

**Comment by aantron** [comment]
(I just looked through the files being added, and, again, most of them come from dev packages that are needed only for the examples rather than genuinely for luv, luv_promise, or luv_lwt)

**Comment by lessp** [comment]
> As for the NPM `reason-promise` package, that's the JS version of `promise` (and the main one). But it can't be used by luv, because luv is native :) This is a dep on the native implementation of promise (from its `src/native` dir), which is not released to opam, so has to be built from the dev repo ATM, or, again, it's easier to just remove it :)

Ah, yes, forgot about that, thanks!

> This error looks like esy is misinterpreting the opam file, or something like that:
> 
> ```
> No package matching:
>   luv -> @opam/luv -> @opam/promise@>=opam:1.0.0
> ```
> 
> because `promise` is only a `dev` dep, because it is needed for two of the examples:
> 
> https://github.com/aantron/luv/blob/e0788bd840219427a2744963f11fff68f2d20087/luv.opam#L28
> 
> Does esy assume that `luv` resolved to a repo is a dev build, and therefore try to pull this dependency?
> 
> Also, `promise` has an opam resolution, but I think it shouldn't be installed at all:
> 
> https://github.com/aantron/luv/blob/e0788bd840219427a2744963f11fff68f2d20087/luv.opam#L31-L33
> 
> I can probably just remove it from the opam file, and have Travis install it manually for its build.

I'll see if I can find some time to see if there's an issue with how `esy` interprets this. I'd leave the `.opam`-file as is, it could be helpful. 🙂

**Comment by lessp** [comment]
I'll close this as not to create any unnecessary noise until I've got some time to explore further!

**Comment by aantron** [comment]
FYI I removed most of the `dev` deps from the opam file in 4a2aaa6f3a1dbb5737d68363e5620fbf94acf331, which might make this PR easier.

**Pull request closed without merging**
