### PR TITLE
Add FreeBSD support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
My local virtualized freebsd is a bit slow so testing here using Travis CI.

The issue on FreeBSD is that the default make command is BSD make, not GNU make (which is required)

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
ah, I see you're not using Travis CI anymore and github action doesn't support BSDs yet.
I've converted the Travis script to test only FreeBSD if you want to enable it as well. Here is the Travis build that I've enabled on my fork to prove this fixes the issue: https://travis-ci.org/github/kit-ty-kate/luv/builds/707672562 (it's all green)

**Comment by aantron** [comment]
I am using Travis, for fast feedback. Travis is probably just having issues reporting status at the moment, which it seems to have had several times over the last few months, or it's something else I have to look at again. Could you restore the previous Travis rows?

**Comment by aantron** [comment]
Also, the Windows build is failing. It's not due to any of the warnings in the log (those are caused by Ctypes and are not fatal). My first guess is it is due to `gmake` perhaps not being available in typical Cygwin environments, such as the one used by opam-repository-mingw and the one distributed by esy. I'm not sure if that's properly a Dune issue (of which command it chooses to run), but I couldn't release Luv with a newly-broken Windows build in any case.

**Comment by kit-ty-kate** [comment]
Sorry for Travis, it is fixed now and all green: https://travis-ci.org/github/aantron/luv/builds/707711320

About Cygwin I'm not sure why it's failing. Looking at how dune detects whether to use gmake, it might be an issue, but I'm not sure what a `gmake` binary would be if it's not GNU make: https://github.com/ocaml/dune/blob/5c1f104088d277e51af18ab79698fc70b068f934/src/stdune/bin.ml#L43

**Comment by kit-ty-kate** [comment]
This should be fixed now hopefully. The issue was that – as you said – gmake is not installed by Cygwin and Dune detects whether to use gmake or make by first detecting if gmake exists, if it is then use it, otherwise use make. However in this CI environment Strawberry Perl was installed and in the path, and it is installed with `gmake`, so dune just used it (`C:\Strawberry\c\bin\gmake.exe`).

My fix is to use `%{make}` if we're in a Unix environment (Linux or BSD) or `make` otherwise (Win32 or Cygwin)

**Comment by kit-ty-kate** [comment]
All green. Though if you decide not to use this I understand and will not delay the release of 0.5.4 any longer.

**Comment by aantron** [comment]
I won't have time to properly review this until probably the next libuv release, but I do want to include it. Would you mind letting the 0.5.4 release proceed? I wasn't explicitly trying to support FreeBSD as of 0.5.4, but I will support it in future releases.

**Comment by kit-ty-kate** [comment]
Sure, I just merged it. Sorry for the bother

**Comment by aantron** [comment]
Thanks!

**Pull request merged**
